name: moshi
description: ChatMoshi helps you learn a second language by speaking it.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 23.9.4+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.1.0
  cloud_firestore: ^4.8.3
  cloud_functions: ^4.4.0
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.6
  firebase_storage: ^11.2.5
  flutter_cache_manager: ^3.3.1
  google_sign_in: ^6.1.4
  http: ^1.1.0
  path_provider: ^2.1.1
  record: ^4.4.4
  shared_preferences: ^2.2.0
  flutter_heatmap_calendar: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

# run: flutter pub get && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: Plex
      fonts:
        - asset: assets/fonts/IBMPlexSerif-Regular.ttf
