name: moshi_client
description: The client for Moshi.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 23.7.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  # sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.0
  http: ^1.1.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.0
  go_router: ^9.0.3
  provider: ^6.0.5
  record: ^4.4.4
  audioplayers: ^0.18.3
  flutter_cache_manager: ^3.3.1
  firebase_storage: ^11.2.5
  mic_stream: ^0.6.5
  flutter_webrtc: ^0.9.36
  # record:
  #   git:
  #     url: git@github.com:llfbandit/record.git
  #     ref: cd38fbb97261af7402051380e96be4cd27b8a13e
  #     path: record

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
