// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLqltqpYoJ7OmMu216rX8oGQadx2zM8mY',
    appId: '1:462213871057:web:a25b22832e16adc5a19cf0',
    messagingSenderId: '462213871057',
    projectId: 'moshi-3',
    authDomain: 'moshi-3.firebaseapp.com',
    storageBucket: 'moshi-3.appspot.com',
    measurementId: 'G-FFF1BC04WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiY9BUsA3Rw7DqMguoN_DZ7Jz83thxbzw',
    appId: '1:462213871057:android:45ace2746f6a1f8ca19cf0',
    messagingSenderId: '462213871057',
    projectId: 'moshi-3',
    storageBucket: 'moshi-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_5-v3W294atZ45-p9xjPBwR-kABDUsA',
    appId: '1:462213871057:ios:f12eff6fc2ca8a23a19cf0',
    messagingSenderId: '462213871057',
    projectId: 'moshi-3',
    storageBucket: 'moshi-3.appspot.com',
    iosClientId: '462213871057-pb8qj1caal02cec7753s794m7co848h7.apps.googleusercontent.com',
    iosBundleId: 'com.chatmoshi.moshi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN_5-v3W294atZ45-p9xjPBwR-kABDUsA',
    appId: '1:462213871057:ios:e0a88ee7433f687aa19cf0',
    messagingSenderId: '462213871057',
    projectId: 'moshi-3',
    storageBucket: 'moshi-3.appspot.com',
    iosClientId: '462213871057-fob3m0kof31gm1i5ld0p37a7ar2odrs8.apps.googleusercontent.com',
    iosBundleId: 'com.chatmoshi.moshi.RunnerTests',
  );
}
